# Generated by Django 3.0.6 on 2020-06-19 19:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_auto_20200619_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
