# Generated by Django 3.0.7 on 2020-10-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_flashcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
    ]
