# Generated by Django 3.0.7 on 2020-10-23 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_auto_20201023_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='category',
        ),
    ]
