# Generated by Django 3.0.7 on 2020-10-23 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0010_remove_flashcard_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='problems.Category'),
            preserve_default=False,
        ),
    ]
