# Generated by Django 3.0.7 on 2020-10-25 19:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0012_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='user',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
