# Generated by Django 3.0.7 on 2020-12-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0013_auto_20201025_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='left_exact',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='right_exact',
        ),
        migrations.AddField(
            model_name='rule',
            name='flip',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='left_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rule',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='rule',
            name='right_min',
            field=models.IntegerField(default=0),
        ),
    ]
