version: '3.1'

services:
  # The DB is going to be installed on the server
  web:
    build: .
    command: "python manage.py runserver 0.0.0.0:${APP_PORT}"
    volumes:
      - .:/code
    ports:
      - "80:${APP_PORT}"
    networks:
      - mathfacter
    logging:
      options:
        max-size: "500k"
        max-file: "1"

  frontend:
    image: node:12
    volumes:
      - '../mathfacter-frontend:/app'
    networks:
      - mathfacter
    ports:
      - '3000:3000'
    user: 'node'
    command: sh -c 'npm i && npm run start'
    working_dir: '/app'
    # This prevents webpack from exiting
    stdin_open: true
    logging:
      options:
        max-size: "500k"
        max-file: "1"

networks:
  mathfacter:
