version: '3.1'

services:
  db:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 2opkj2ertcznsskjxiojc
      MYSQL_DATABASE: mathfacter
    volumes:
      - mathfacter-data:/var/lib/mysql
    networks:
      - mathfacter
    logging:
      options:
        max-size: "500k"
        max-file: "1"

  web:
    build: .
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "80:8000"
    networks:
      - mathfacter
    logging:
      options:
        max-size: "500k"
        max-file: "1"

  frontend:
    image: node:12
    volumes:
      - '../mathfacter-frontend:/app'
    networks:
      - mathfacter
    ports:
      - '3000:3000'
    user: 'node'
    command: sh -c 'npm i && npm run start'
    working_dir: '/app'
    # This prevents webpack from exiting
    stdin_open: true
    logging:
      options:
        max-size: "500k"
        max-file: "1"

networks:
  mathfacter:
volumes:
  mathfacter-data:
