version: '3.1'

services:
  # The DB is going to be installed on the server
  # db:
  web:
    build: .
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "80:8000"
    networks:
      - mathfacter
    logging:
      options:
        max-size: "500k"
        max-file: "1"

  frontend:
    image: node:10
    volumes:
      - './frontend:/app'
    networks:
      - mathfacter
    ports:
      - '3000:3000'
    user: 'node'
    command: sh -c 'npm i && npm run start'
    working_dir: '/app'
    logging:
      options:
        max-size: "500k"
        max-file: "1"

networks:
  mathfacter:
